name: editor-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  PROJECT_ID_EMAIL: ${{ secrets.PROJECT_ID_EMAIL }}
  RENDERER_SERVICE_URL: ${{ secrets.RENDERER_SERVICE_URL }}
  CLOUD_RUN_REGION: us-central1
  REPO_NAME: editorsvc

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # This step is where our service account will be authenticated
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}      

    - name: Enable docker auth
      run: |-
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable run.googleapis.com      
        gcloud --quiet auth configure-docker
        
    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
        
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
        
    - name: Deploy
      run: |-
        gcloud components install beta --quiet  
        gcloud alpha iam policies lint-condition
        gcloud run services add-iam-policy-binding renderer \
          --member serviceAccount:editor-identity \
          --role roles/run.invoker \
          --region $CLOUD_RUN_REGION
        gcloud beta run deploy editor --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA --allow-unauthenticated \
          --service-account editor-identity \
          --project $CLOUD_RUN_PROJECT_ID \
          --platform managed \
          --set-env-vars EDITOR_UPSTREAM_RENDER_URL=$RENDERER_SERVICE_URL \
          --region $CLOUD_RUN_REGION          
