name: Provisioning infrastructure and Deployment for editor CloudRun


on: 
  push:
    branches:
      - feat-tf
      
env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA }}
  REPO_NAME: editor
  RUN_REGION: europe-west1
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
jobs:
  setup-build-deploy-cloudrun:
    name: "Setup, Build, and Deploy CloudRun- '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # Setup gcloud CLI  
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA}}
        export_default_credentials: true
        project_id: ${{ env.CLOUD_RUN_PROJECT_ID }} 
        
    - name: Create tf state bucket    
      run: |-
        if ! gsutil ls | grep gs://$BUCKET_NAME ;then gsutil mb -p $PROJECT_ID -l $RUN_REGION -b on gs://$BUCKET_NAME;fi   
                
    - name: Enable docker auth
      run: |-     
        gcloud --quiet auth configure-docker
        
    - name: Build and tag image
      run: |-
        docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
        
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA          
  
    # Terraform remote state GCS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Terraform init
      id: init
      run: |-
        mv gcp/service/cloudrun/backend.tf .
        terraform init  -backend-config="bucket=$BUCKET_NAME" -backend-config="prefix=dev"
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
    - name: Terraform Plan
      id: plan
      run: |-
        export RENDERER_SERVICE_URL=""
        if gcloud run services list --platform managed | grep renderer | awk '{print $4}' ;then RENDERER_SERVICE_URL=$(gcloud run services list --platform managed | grep renderer | awk '{print $4}');fi
         terraform plan \
          -var="project_id=$PROJECT_ID" \
          -var="region=$RUN_REGION" \
          -var="service_name=$REPO_NAME" \
          -var="docker_image=gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA" \
          -var="port=80" \
          -var="service_account_id=cloudrun-identity" \
          -var="service_account_name=cloudrun-identity" \
          -var="cloudrun_service_account=cloudrun-identity@PROJECT_ID.iam.gserviceaccount.com" \
          -var="invoker_member=allUsers" \
          -var="vendor=gcp" \
          -var="vendor_service=cloudrun" \
          -var="env_key=renderer_svc_url" \
          -var="env_value=$RENDERER_SERVICE_URL" \
          -out=PLAN
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
    - name: Terraform apply
      id: apply
      run: |-
        terraform apply PLAN
      continue-on-error: false
      working-directory: ./tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS}}
